services:
  mqttop:
    image: ghcr.io/lone-faerie/mqttop:latest
    container_name: mqttop
    environment:
      - MQTTOP_ROOTFS_PATH=/host
      - MQTTOP_BROKER_ADDRESS="127.0.0.1:1883"
      - MQTTOP_BROKER_USERNAME=mqttop
      - MQTTOP_BROKER_PASSWORD=password
    volumes:
      - "./cmd/config.yml:/config/config.yml"
      - "/:/host:ro"
    network_mode: host
