services:
  mqttop:
    image: ghcr.io/lone-faerie/mqttop:latest
    container_name: mqttop
    environment:
      - MQTTOP_ROOTFS_PATH=/host
    volumes:
      - "./cmd/config.yml:/config/config.yml"
      - "/:/host:ro"
    network_mode: host
