services:
  mqttop:
    image: ghcr.io/lone-faerie/mqttop:gpu
    environment:
      - MQTTOP_ROOTFS_PATH=/host
    volumes:
      - "./cmd/config.yml:/config/config.yml"
      - "/:/host:ro"
    network_mode: host
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
