name: Gopkg

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

jobs:
  gopkg:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          curl https://proxy.golang.org/github.com/lone-faerie/mqttop/@v/@${{ github.ref_name }}.info
