name: Gopkg

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

jobs:
  gopkg:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          curl https://sum.golang.org/lookup/github.com/lone-faerie/mqttop@${{ github.ref_name }}
